// Self-hosted Studio on a hosting platform: the auth service's settings. The platform
// keeps them as the service's environment (GOTRUE_<KEY>), all strings; the native screens
// expect the hosted config object with booleans and numbers. Server-side only.
import { call, type PlatformResult } from './platform-backups'

// Generated from the hosted GoTrueConfigResponse type. Template contents are left out: the
// auth service takes templates by URL, not as text.
const BOOLEAN_KEYS = [
  'AUDIT_LOG_DISABLE_POSTGRES',
  'CUSTOM_OAUTH_ENABLED',
  'DISABLE_SIGNUP',
  'EXTERNAL_ANONYMOUS_USERS_ENABLED',
  'EXTERNAL_APPLE_EMAIL_OPTIONAL',
  'EXTERNAL_APPLE_ENABLED',
  'EXTERNAL_AZURE_EMAIL_OPTIONAL',
  'EXTERNAL_AZURE_ENABLED',
  'EXTERNAL_BITBUCKET_EMAIL_OPTIONAL',
  'EXTERNAL_BITBUCKET_ENABLED',
  'EXTERNAL_DISCORD_EMAIL_OPTIONAL',
  'EXTERNAL_DISCORD_ENABLED',
  'EXTERNAL_EMAIL_ENABLED',
  'EXTERNAL_FACEBOOK_EMAIL_OPTIONAL',
  'EXTERNAL_FACEBOOK_ENABLED',
  'EXTERNAL_FIGMA_EMAIL_OPTIONAL',
  'EXTERNAL_FIGMA_ENABLED',
  'EXTERNAL_GITHUB_EMAIL_OPTIONAL',
  'EXTERNAL_GITHUB_ENABLED',
  'EXTERNAL_GITLAB_EMAIL_OPTIONAL',
  'EXTERNAL_GITLAB_ENABLED',
  'EXTERNAL_GOOGLE_EMAIL_OPTIONAL',
  'EXTERNAL_GOOGLE_ENABLED',
  'EXTERNAL_GOOGLE_SKIP_NONCE_CHECK',
  'EXTERNAL_KAKAO_EMAIL_OPTIONAL',
  'EXTERNAL_KAKAO_ENABLED',
  'EXTERNAL_KEYCLOAK_EMAIL_OPTIONAL',
  'EXTERNAL_KEYCLOAK_ENABLED',
  'EXTERNAL_LINKEDIN_OIDC_EMAIL_OPTIONAL',
  'EXTERNAL_LINKEDIN_OIDC_ENABLED',
  'EXTERNAL_NOTION_EMAIL_OPTIONAL',
  'EXTERNAL_NOTION_ENABLED',
  'EXTERNAL_PHONE_ENABLED',
  'EXTERNAL_SLACK_EMAIL_OPTIONAL',
  'EXTERNAL_SLACK_ENABLED',
  'EXTERNAL_SLACK_OIDC_EMAIL_OPTIONAL',
  'EXTERNAL_SLACK_OIDC_ENABLED',
  'EXTERNAL_SPOTIFY_EMAIL_OPTIONAL',
  'EXTERNAL_SPOTIFY_ENABLED',
  'EXTERNAL_TWITCH_EMAIL_OPTIONAL',
  'EXTERNAL_TWITCH_ENABLED',
  'EXTERNAL_TWITTER_EMAIL_OPTIONAL',
  'EXTERNAL_TWITTER_ENABLED',
  'EXTERNAL_WEB3_ETHEREUM_ENABLED',
  'EXTERNAL_WEB3_SOLANA_ENABLED',
  'EXTERNAL_ZOOM_EMAIL_OPTIONAL',
  'EXTERNAL_ZOOM_ENABLED',
  'HOOK_AFTER_USER_CREATED_ENABLED',
  'HOOK_BEFORE_USER_CREATED_ENABLED',
  'HOOK_CUSTOM_ACCESS_TOKEN_ENABLED',
  'HOOK_MFA_VERIFICATION_ATTEMPT_ENABLED',
  'HOOK_PASSWORD_VERIFICATION_ATTEMPT_ENABLED',
  'HOOK_SEND_EMAIL_ENABLED',
  'HOOK_SEND_SMS_ENABLED',
  'INDEX_WORKER_ENSURE_USER_SEARCH_INDEXES_EXIST',
  'MAILER_ALLOW_UNVERIFIED_EMAIL_SIGN_INS',
  'MAILER_AUTOCONFIRM',
  'MAILER_NOTIFICATIONS_EMAIL_CHANGED_ENABLED',
  'MAILER_NOTIFICATIONS_IDENTITY_LINKED_ENABLED',
  'MAILER_NOTIFICATIONS_IDENTITY_UNLINKED_ENABLED',
  'MAILER_NOTIFICATIONS_MFA_FACTOR_ENROLLED_ENABLED',
  'MAILER_NOTIFICATIONS_MFA_FACTOR_UNENROLLED_ENABLED',
  'MAILER_NOTIFICATIONS_PASSWORD_CHANGED_ENABLED',
  'MAILER_NOTIFICATIONS_PHONE_CHANGED_ENABLED',
  'MAILER_SECURE_EMAIL_CHANGE_ENABLED',
  'MFA_ALLOW_LOW_AAL',
  'MFA_PHONE_ENROLL_ENABLED',
  'MFA_PHONE_VERIFY_ENABLED',
  'MFA_TOTP_ENROLL_ENABLED',
  'MFA_TOTP_VERIFY_ENABLED',
  'MFA_WEB_AUTHN_ENROLL_ENABLED',
  'MFA_WEB_AUTHN_VERIFY_ENABLED',
  'OAUTH_SERVER_ALLOW_DYNAMIC_REGISTRATION',
  'OAUTH_SERVER_ENABLED',
  'PASSKEY_ENABLED',
  'PASSWORD_HIBP_ENABLED',
  'REFRESH_TOKEN_ROTATION_ENABLED',
  'SAML_ALLOW_ENCRYPTED_ASSERTIONS',
  'SAML_ENABLED',
  'SECURITY_CAPTCHA_ENABLED',
  'SECURITY_MANUAL_LINKING_ENABLED',
  'SECURITY_SB_FORWARDED_FOR_ENABLED',
  'SECURITY_UPDATE_PASSWORD_REQUIRE_CURRENT_PASSWORD',
  'SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION',
  'SESSIONS_SINGLE_PER_USER',
  'SMS_AUTOCONFIRM',
] as const
const NUMBER_KEYS = [
  'API_MAX_REQUEST_DURATION',
  'CUSTOM_OAUTH_MAX_PROVIDERS',
  'JWT_EXP',
  'MAILER_OTP_EXP',
  'MAILER_OTP_LENGTH',
  'MFA_MAX_ENROLLED_FACTORS',
  'MFA_PHONE_MAX_FREQUENCY',
  'MFA_PHONE_OTP_LENGTH',
  'PASSWORD_MIN_LENGTH',
  'RATE_LIMIT_ANONYMOUS_USERS',
  'RATE_LIMIT_EMAIL_SENT',
  'RATE_LIMIT_OTP',
  'RATE_LIMIT_SMS_SENT',
  'RATE_LIMIT_TOKEN_REFRESH',
  'RATE_LIMIT_VERIFY',
  'RATE_LIMIT_WEB3',
  'SECURITY_REFRESH_TOKEN_REUSE_INTERVAL',
  'SESSIONS_INACTIVITY_TIMEOUT',
  'SESSIONS_TIMEBOX',
  'SMS_MAX_FREQUENCY',
  'SMS_OTP_EXP',
  'SMS_OTP_LENGTH',
  'SMTP_MAX_FREQUENCY',
] as const
const STRING_KEYS = [
  'EXTERNAL_APPLE_ADDITIONAL_CLIENT_IDS',
  'EXTERNAL_APPLE_CLIENT_ID',
  'EXTERNAL_APPLE_SECRET',
  'EXTERNAL_AZURE_CLIENT_ID',
  'EXTERNAL_AZURE_SECRET',
  'EXTERNAL_AZURE_URL',
  'EXTERNAL_BITBUCKET_CLIENT_ID',
  'EXTERNAL_BITBUCKET_SECRET',
  'EXTERNAL_DISCORD_CLIENT_ID',
  'EXTERNAL_DISCORD_SECRET',
  'EXTERNAL_FACEBOOK_CLIENT_ID',
  'EXTERNAL_FACEBOOK_SECRET',
  'EXTERNAL_FIGMA_CLIENT_ID',
  'EXTERNAL_FIGMA_SECRET',
  'EXTERNAL_GITHUB_CLIENT_ID',
  'EXTERNAL_GITHUB_SECRET',
  'EXTERNAL_GITLAB_CLIENT_ID',
  'EXTERNAL_GITLAB_SECRET',
  'EXTERNAL_GITLAB_URL',
  'EXTERNAL_GOOGLE_ADDITIONAL_CLIENT_IDS',
  'EXTERNAL_GOOGLE_CLIENT_ID',
  'EXTERNAL_GOOGLE_SECRET',
  'EXTERNAL_KAKAO_CLIENT_ID',
  'EXTERNAL_KAKAO_SECRET',
  'EXTERNAL_KEYCLOAK_CLIENT_ID',
  'EXTERNAL_KEYCLOAK_SECRET',
  'EXTERNAL_KEYCLOAK_URL',
  'EXTERNAL_LINKEDIN_OIDC_CLIENT_ID',
  'EXTERNAL_LINKEDIN_OIDC_SECRET',
  'EXTERNAL_NOTION_CLIENT_ID',
  'EXTERNAL_NOTION_SECRET',
  'EXTERNAL_SLACK_CLIENT_ID',
  'EXTERNAL_SLACK_OIDC_CLIENT_ID',
  'EXTERNAL_SLACK_OIDC_SECRET',
  'EXTERNAL_SLACK_SECRET',
  'EXTERNAL_SPOTIFY_CLIENT_ID',
  'EXTERNAL_SPOTIFY_SECRET',
  'EXTERNAL_TWITCH_CLIENT_ID',
  'EXTERNAL_TWITCH_SECRET',
  'EXTERNAL_TWITTER_CLIENT_ID',
  'EXTERNAL_TWITTER_SECRET',
  'EXTERNAL_WORKOS_CLIENT_ID',
  'EXTERNAL_WORKOS_SECRET',
  'EXTERNAL_WORKOS_URL',
  'EXTERNAL_ZOOM_CLIENT_ID',
  'EXTERNAL_ZOOM_SECRET',
  'HOOK_AFTER_USER_CREATED_SECRETS',
  'HOOK_AFTER_USER_CREATED_URI',
  'HOOK_BEFORE_USER_CREATED_SECRETS',
  'HOOK_BEFORE_USER_CREATED_URI',
  'HOOK_CUSTOM_ACCESS_TOKEN_SECRETS',
  'HOOK_CUSTOM_ACCESS_TOKEN_URI',
  'HOOK_MFA_VERIFICATION_ATTEMPT_SECRETS',
  'HOOK_MFA_VERIFICATION_ATTEMPT_URI',
  'HOOK_PASSWORD_VERIFICATION_ATTEMPT_SECRETS',
  'HOOK_PASSWORD_VERIFICATION_ATTEMPT_URI',
  'HOOK_SEND_EMAIL_SECRETS',
  'HOOK_SEND_EMAIL_URI',
  'HOOK_SEND_SMS_SECRETS',
  'HOOK_SEND_SMS_URI',
  'MAILER_SUBJECTS_CONFIRMATION',
  'MAILER_SUBJECTS_CUSTOM_CONTENTS',
  'MAILER_SUBJECTS_EMAIL_CHANGE',
  'MAILER_SUBJECTS_EMAIL_CHANGED_NOTIFICATION',
  'MAILER_SUBJECTS_IDENTITY_LINKED_NOTIFICATION',
  'MAILER_SUBJECTS_IDENTITY_UNLINKED_NOTIFICATION',
  'MAILER_SUBJECTS_INVITE',
  'MAILER_SUBJECTS_MAGIC_LINK',
  'MAILER_SUBJECTS_MFA_FACTOR_ENROLLED_NOTIFICATION',
  'MAILER_SUBJECTS_MFA_FACTOR_UNENROLLED_NOTIFICATION',
  'MAILER_SUBJECTS_PASSWORD_CHANGED_NOTIFICATION',
  'MAILER_SUBJECTS_PHONE_CHANGED_NOTIFICATION',
  'MAILER_SUBJECTS_REAUTHENTICATION',
  'MAILER_SUBJECTS_RECOVERY',
  'MFA_PHONE_TEMPLATE',
  'NIMBUS_OAUTH_CLIENT_ID',
  'NIMBUS_OAUTH_CLIENT_SECRET',
  'OAUTH_SERVER_AUTHORIZATION_PATH',
  'PASSWORD_REQUIRED_CHARACTERS',
  'SAML_EXTERNAL_URL',
  'SECURITY_CAPTCHA_PROVIDER',
  'SECURITY_CAPTCHA_SECRET',
  'SESSIONS_TAGS',
  'SITE_URL',
  'SMS_MESSAGEBIRD_ACCESS_KEY',
  'SMS_MESSAGEBIRD_ORIGINATOR',
  'SMS_PROVIDER',
  'SMS_TEMPLATE',
  'SMS_TEST_OTP',
  'SMS_TEST_OTP_VALID_UNTIL',
  'SMS_TEXTLOCAL_API_KEY',
  'SMS_TEXTLOCAL_SENDER',
  'SMS_TWILIO_ACCOUNT_SID',
  'SMS_TWILIO_AUTH_TOKEN',
  'SMS_TWILIO_CONTENT_SID',
  'SMS_TWILIO_MESSAGE_SERVICE_SID',
  'SMS_TWILIO_VERIFY_ACCOUNT_SID',
  'SMS_TWILIO_VERIFY_AUTH_TOKEN',
  'SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID',
  'SMS_VONAGE_API_KEY',
  'SMS_VONAGE_API_SECRET',
  'SMS_VONAGE_FROM',
  'SMTP_ADMIN_EMAIL',
  'SMTP_HOST',
  'SMTP_PASS',
  'SMTP_PORT',
  'SMTP_SENDER_NAME',
  'SMTP_USER',
  'URI_ALLOW_LIST',
  'WEBAUTHN_RP_DISPLAY_NAME',
  'WEBAUTHN_RP_ID',
  'WEBAUTHN_RP_ORIGINS',
] as const

// What the auth service does when a setting is not set.
const DEFAULTS: Record<string, boolean | number> = {
  EXTERNAL_EMAIL_ENABLED: true,
  MAILER_SECURE_EMAIL_CHANGE_ENABLED: true,
  MFA_TOTP_ENROLL_ENABLED: true,
  MFA_TOTP_VERIFY_ENABLED: true,
  REFRESH_TOKEN_ROTATION_ENABLED: true,
  API_MAX_REQUEST_DURATION: 10,
  JWT_EXP: 3600,
  MAILER_OTP_EXP: 3600,
  MAILER_OTP_LENGTH: 6,
  MFA_MAX_ENROLLED_FACTORS: 10,
  PASSWORD_MIN_LENGTH: 6,
  RATE_LIMIT_ANONYMOUS_USERS: 30,
  RATE_LIMIT_EMAIL_SENT: 30,
  RATE_LIMIT_OTP: 30,
  RATE_LIMIT_SMS_SENT: 30,
  RATE_LIMIT_TOKEN_REFRESH: 150,
  RATE_LIMIT_VERIFY: 30,
  RATE_LIMIT_WEB3: 30,
  SECURITY_REFRESH_TOKEN_REUSE_INTERVAL: 10,
  SMS_MAX_FREQUENCY: 60,
  SMS_OTP_EXP: 60,
  SMS_OTP_LENGTH: 6,
  SMTP_MAX_FREQUENCY: 60,
}

const BOOLEANS = new Set<string>(BOOLEAN_KEYS)
const NUMBERS = new Set<string>(NUMBER_KEYS)
const STRINGS = new Set<string>(STRING_KEYS)

export type AuthConfig = Record<string, boolean | number | string | null>

const base = () =>
  `/api/apps/${encodeURIComponent(process.env.KUBERO_PIPELINE ?? '')}/${encodeURIComponent(
    process.env.KUBERO_PHASE ?? ''
  )}/${encodeURIComponent(
    (process.env.KUBERO_DB_INSTANCE ?? '').replace(/-postgresql$/, '')
  )}/group/config/auth`

/** The service's string settings as the hosted config object, every known key present. */
export function toAuthConfig(settings: Record<string, string>): AuthConfig {
  const config: AuthConfig = {}
  for (const key of BOOLEAN_KEYS) {
    const raw = settings[key]
    config[key] = raw === undefined ? DEFAULTS[key] === true : raw.trim().toLowerCase() === 'true'
  }
  for (const key of NUMBER_KEYS) {
    const parsed = Number(settings[key])
    config[key] =
      settings[key] !== undefined && settings[key].trim() !== '' && Number.isFinite(parsed)
        ? parsed
        : ((DEFAULTS[key] as number | undefined) ?? 0)
  }
  for (const key of STRING_KEYS) config[key] = settings[key] ?? null
  return config
}

/** Changes from the native forms as settings for the service: null removes one. Unknown keys are dropped. */
export function toSettingChanges(changes: Record<string, unknown>): Record<string, string | null> {
  const out: Record<string, string | null> = {}
  for (const [key, value] of Object.entries(changes ?? {})) {
    if (value === undefined) continue
    if (BOOLEANS.has(key)) out[key] = value === true || value === 'true' ? 'true' : 'false'
    else if (NUMBERS.has(key)) {
      if (value === null || value === '') out[key] = null
      else if (Number.isFinite(Number(value))) out[key] = String(Number(value))
    } else if (STRINGS.has(key)) out[key] = value === null || value === '' ? null : String(value)
  }
  return out
}

export async function getAuthConfig(): Promise<PlatformResult<AuthConfig>> {
  const result = await call<Record<string, string>>('GET', base())
  if (result.error) return { error: result.error }
  return { data: toAuthConfig(result.data) }
}

export async function updateAuthConfig(
  changes: Record<string, unknown>
): Promise<PlatformResult<AuthConfig>> {
  const result = await call<Record<string, string>>('PATCH', base(), toSettingChanges(changes))
  if (result.error) return { error: result.error }
  return { data: toAuthConfig(result.data) }
}
